### ISSUE TITLE
Buggy code in the correct directory GENERATE_INTEGERS

### ISSUE THREAD

**Issue by BEbillionaireUSD** [ASSERT-KTH/human-eval-java#2]
Content in the `src/java/humaneval/correct` is:
```
// Given two positive integers a and b, return the even digits between a
// and b, in ascending order.

// For example:
// generate_integers(2, 8) => [2, 4, 6, 8]
// generate_integers(8, 2) => [2, 4, 6, 8]
// generate_integers(10, 14) => []

public class GENERATE_INTEGERS {
    public static ArrayList<Integer> generate_integers(int a, int b) {
        int lower = Math.max(2, Math.min(a, b));
        int upper = Math.min(8, Math.max(a, b));

        ArrayList<Integer> result = new ArrayList<Integer>();
        for (int i = lower; i <= upper; i += 1) {
            if (i % 2 == 0) result.add(i);
        }
        return result;
    }
}
```
The code is faulty, yet its corresponding buggy version is correct. The right one and the wrong one are reversed. 
The test code is also faulty.

**Comment by ZodPSC** [comment]
hm...
GENERATE_INTEGERS.generate_integers(2,8); //[4, 6]
GENERATE_INTEGERS.generate_integers(8,2); //[4, 6]
GENERATE_INTEGERS.generate_integers(7,1); //[2, 4, 6]

            int lower = Math.min(a, b);
            int upper = lower == a ? b : a;

            ArrayList<Integer> result = new ArrayList<Integer>();
            for (int i = lower + 1; i < upper; i += 1) {
                if (i % 2 == 0) result.add(i);
            }
            return result;

**Comment by andre15silva** [comment]
Hi!

Thanks for reporting this problem. Could you open a PR to fix this?

Also, please note that we do not maintain this benchmark. This is simply a fork of the original repo (https://github.com/lin-tan/clm)

**Comment by ZodPSC** [comment]
https://github.com/ASSERT-KTH/human-eval-java/pull/3

**Comment by ZodPSC** [comment]
I have an error when extracting that archive. so I corrected the sources here and created a pull request.

**Comment by BEbillionaireUSD** [comment]
Thanks for your discussion. I think I misunderstood the original description. I guess "even digits" are defined as [0, 2, 4, 6, 8], so if the lower bound is larger than 8, then the function should return an empty list.
